### ISSUE TITLE
[Android Bootcamp] Project 2: Grid Image Search - Ready for Review

### ISSUE THREAD

**Issue by hashamali** [hashamali/SimpleImageSearch#1]
Ready for review. All advanced and bonus features implemented.

### Reviewers
- [ ] @codepathreview 
- [ ] @codepath

**Comment by codepathreview** [comment]
:+1: Excellent submission once again, Hasham! Thanks for putting in so much effort in these assignments, hope you're having fun learning all new things about Android. Few notes:

* Correctly named packages and organized source files
* Properly used spinners (with populated values) to allow users to select filters
* Nice work setting up shared preferences to persist the settings
* Excellent polished UI/UX including modal overlay/animations/cardview/etc.
* Nice job adding the share intent via popup menu
* Good job using Parcelable instead of Serializable ([benefits](http://stackoverflow.com/a/5551155))
* Nice to see you added the search box to the ActionBar!
* Correctly used `StaggeredGridView` and `TouchImageView` 
* Consider adding [progress bars](http://guides.codepath.com/android/Handling-ProgressBars#actionbar-progress-bar) to your app whenever a network request goes out in addition to the placeholder images.

Also, here's a more detailed [Project 2 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) which covers the most common issues with this submitted project. Read through the [feedback guide point-by-point](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.
